spring.application.name=msvc-team-service

server.port=8084

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:teamdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true