spring.application.name=msvc-user

server.port=8083

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true